### PR TITLE
contributors base for approbation

### PR DESCRIPTION
**Pull request by ErickLemos**

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey @ErickLemos 
I don't quite understand this ?

**Comment by ErickLemos** [comment]
is a new section on about page:
Captura de tela de 2020-10-09 08-56-06

**Comment by lelouchB** [comment]
I don't think this will be feasile. I mean to include all the contributors, there are about 20 contributors right now. Maybe more in future.

To add some and ignore other is not okay. I mean even the order is enough to cause conflcits among contributors. Why is someone above me? Is it based on a commit? Files Chnages? PR merged? I don't want to indulge in all this.

I am working on adding a contributors-img to Readme. 
https://contributors-img.web.app/preview?repo=lelouchB%2Ffinal-space-api

Hope you understand,

Thanks

**Comment by ErickLemos** [comment]
Sure, i undestand!

**Pull request closed without merging**
