### PR TITLE
added eslint with base in project style code

### PR DESCRIPTION
**Pull request by ErickLemos**

### CODE REVIEW

**Review by lelouchB — APPROVED** [review]
@ErickLemos 
This is awesome 👌 
I have been meaning to crate an issue for lint.

Thanks for this.

I will merge and ship this to production sometime tommorow.

**Comment by lelouchB** [comment]
Can you also add a npm script for this?

**Comment by JuanVqz** [comment]
don't forget to integrate prettier with eslint, please and thank you

**Comment by ErickLemos** [comment]
okay, i will do this

**Comment by ErickLemos** [comment]
Ready

**Review by lelouchB — APPROVED** [review]

**Pull request merged**
