### PR TITLE
Add react axios example

### PR DESCRIPTION
**Pull request by fernandoamz**
Add react axios example

This is a part of the issue #32

Screen Shot 2020-10-07 at 12 17 01 PM

### CODE REVIEW

**Review by lelouchB — APPROVED** [review]

**Comment by lelouchB** [comment]
@fernandoamz Great Work,
I was thinking since this example is quire similar to `react` example, maybe we can add a **TAB** in the `react` example for this.
First one being `React` and the other being `React+Axios`.

Resource : https://v2.docusaurus.io/docs/markdown-features#tabs
Something familair to this
image



Thanks

**Comment by fernandoamz** [comment]
Yeah, I will add as a tab form. I will update as soon as possible.

**Comment by fernandoamz** [comment]
@lelouchB, I added the example as tab, but I am getting conflicts with your original `react.md` I cannot resolve the conflicts the button is locked. but, take a look an tell me what think about the change.

**Comment by lelouchB** [comment]
Hey @fernandoamz 
There has been some updates in the repo, also in `react.md` file.

You need to update your branch to resolve these conflicts.

**Comment by fernandoamz** [comment]
@lelouchB, I could fix the conflicts

**Comment by fernandoamz** [comment]
@lelouchB, If the changes are accepted. May you add the `hacktoberfest-accepted` tag? 

Screen Shot 2020-10-07 at 1 12 20 PM

**Comment by lelouchB** [comment]
> 
> 
> @lelouchB, If the changes are accepted. May you add the `hacktoberfest-accepted` tag?
> 
> Screen Shot 2020-10-07 at 1 12 20 PM

I have approved it and will merge it soon so it should be okay.
But I will still add that label.

Thanks

**Review by lelouchB — APPROVED** [review]

**Pull request merged**
