### PR TITLE
Updates greetings workflow

### PR DESCRIPTION
**Pull request by MrDoomy**
Here are two personalized messages for the first new issue and the first pull request per user.
These messages come from **Gary Goodspeed** (Final Space's season 1).
More information here 👉 https://github.com/lelouchB/final-space-api/issues/107

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey Hey
I never got any reply to the comment, I though it must have got lost in the notifications so I asked for an update..


Looks good to me 
Just resolve that conversation and I will proceed to merge this.

Thanks

**Comment by MrDoomy** [comment]
Hey @lelouchB 👋
No problem! If it's good for you, it's good for me 😉

**Comment by lelouchB** [comment]
Again 
I wanted to just ask what github.actor will do?

I asked it 3 days ago.😁😊

**Comment by MrDoomy** [comment]
Indeed... Notifications hell! 😅
`${{ github.actor }}` is a **github**'s tip, to display the user's login in a notification.
For example, to me, this should display:
> That's Not A Cookie. And You Know That @MrDoomy, You Know That!

**Pull request merged**
