### PR TITLE
chore(linting): Add pre commit hook for prettier

### PR DESCRIPTION
**Pull request by trybick**
Add pre commit hook which will run on every commit
Add npm run lint command you can manually
A few formatting changes are included as a result of linting

I used option 1 on this page (basically just one command!)
https://prettier.io/docs/en/precommit.html#option-1-lint-stagedhttpsgithubcomokonetlint-staged

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey @trybick 
Can you resolve these conflicts?

**Comment by trybick** [comment]
@lelouchB Should be ready for review now

**Comment by lelouchB** [comment]
@trybick 
Great 👍

**Comment by lelouchB** [comment]
Hey @trybick 
Can you resolve the conflicts so I can merge this

**Pull request merged**
