### PR TITLE
Added README for backend

### PR DESCRIPTION
**Pull request by Skr-suyash**
Added README.md file for backend with all the specifications

### CODE REVIEW

**Review by lelouchB — APPROVED** [review]

**Comment by lelouchB** [comment]
Hey @Skr-suyash 
This is great 👍 
Do you mind adding a pic to it.
Also, when referencing a command 
Add it like this 
```bash
npm run dev
```


Then I will merge it.


Also, you did great work with this.
Do you want to work on main README.md too?
If yes, create an issue and assign it yourself .

Thanks

**Comment by Skr-suyash** [comment]
Updated the README with an image of the Final Space Show

**Comment by lelouchB** [comment]
Hey, the images is same as the main README.md
Can you change this to this image instead.

https://github.com/lelouchB/final-space-api/blob/main/frontend/static/img/wallpaper2.jpg


Also, add the code blocks to separate lines and include `bash` after the triple back ticks.

Refer [here](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).

Thanks

**Comment by Skr-suyash** [comment]
No problem will do that

**Comment by lelouchB** [comment]
Hey @Skr-suyash 
I guess there was some confusion, I suggested to change the image in `backend/README.md` and not main `README.md`.

Please Update
Thanks

**Comment by Skr-suyash** [comment]
Sorry, since the files had same name, it created an issue, now is it okay?

**Review by lelouchB — APPROVED** [review]

**Comment by lelouchB** [comment]
Thanks for this amazing contribution @Skr-suyash 
Feel free to update other docs or README.md
Thanks

**Pull request merged**
