### PR TITLE
Added 404 Page

### PR DESCRIPTION
**Pull request by Skr-suyash**
Added the 404 page.
Go to ```baseURL/404"``` to see it.
Check if it is working. 😄😅

### CODE REVIEW

**Comment by lelouchB** [comment]
> Added the 404 page.
> Go to ```baseURL/404"``` to see it.
> Check if it is working. 😄😅
> 

You haven't checked?
Also what about other  routes that doesn't exist?

**Comment by Skr-suyash** [comment]
> You haven't checked?
> Also what about other routes that doesn't exist?
Checked.
But the problem is that Docasaurus has no support for redirecting other routes to 404.
Should I use React Router.
Please check once yourself if it is working.

**Comment by lelouchB** [comment]
Great 👍
I will get to it first thing in the morning.

No need for React router.
This is fine,

Thanks for your work on this.

**Comment by Skr-suyash** [comment]
Hey, is this okay. 😁

**Comment by lelouchB** [comment]
> 
> 
> Hey, is this okay. 😁

Still going through previous PRs, will get to this in a few hours.

Thanks for your patience

**Comment by lelouchB** [comment]
Hey @Skr-suyash 
This looks great, I checked it
The problem is after `npm run build`, if we use `npm run serve` to serve the build folder, all the bad routes are automatically handled by Docusaurus
Here is the page for http://localhost:3000/5

image

But the same is not seen after the `build` folder is deployed with express.

This has become more for a investigation issue.
 Thanks for your work

**Pull request closed without merging**
