### PR TITLE
Example in Angular and Axios

### PR DESCRIPTION
**Pull request by guzbarraf**
Add of operation with Angular and Axios

### CODE REVIEW

**Comment by guzbarraf** [comment]
Hi @lelouchB,
I uploaded the PR with the example of Angular and Axios,
in the same way the example in live is inside,
I share the link [https://codesandbox.io/s/final-space-api-with-angular-and-axios-kstxk](url)

**Comment by guzbarraf** [comment]
@lelouchB 
I had not seen the Labeler error again,
it scared me
😂

**Comment by guzbarraf** [comment]
Hi @lelouchB 
the PR is ok?

**Comment by lelouchB** [comment]
> Hi @lelouchB 
> the PR is ok?

Yes
Will get to it most probably today.

Thanks

**Review by lelouchB — APPROVED** [review]

**Comment by guzbarraf** [comment]
> > Hi @lelouchB
> > the PR is ok?
> 
> Yes, this is great
> Will get to it most probably today. And ship it to production
> 
> Thanks

I liked the project,
if there is more to do I am willing to continue contributing.
Cheers!

**Comment by lelouchB** [comment]
Moving forward I am thinking of adding GraphQL support to the API.

I will let you know once that starts.

Thanks 😊

**Comment by lelouchB** [comment]
Hey @guzbarraf 
It's live, I made some minor changes
https://finalspaceapi.com/docs/angular

Thanks for your contribution

**Comment by guzbarraf** [comment]
> Hey @guzbarraf 
> 
> It's live, I made some minor changes
> 
> https://finalspaceapi.com/docs/angular
> 
> 
> 
> Thanks for your contribution

Looks better

**Comment by guzbarraf** [comment]
Hi @lelouchB
can you still add hacktoberfest labels to these PRs,
so that they count in the hacktoberfest?

**Comment by lelouchB** [comment]
@guzbarraf 
Done

**Pull request merged**
