### PR TITLE
[ADD] episode's data season 1

### PR DESCRIPTION
**Pull request by GerryLarios**
Episode's data

- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 7
- [x] Chapter 8
- [x] Chapter 9
- [x] Chapter 10
- [ ] The Toro Regatta
- [ ] The Happy Place
- [ ] The Grand Surrender
- [ ] The Other Side
- [ ] The Notorious Mrs. Goodspeed
- [ ] The Arachnitects
- [ ] The First Times They Met
- [ ] The Remembered
- [ ] The Closer You Get
- [ ] The Lost Spy
- [ ] The Set Up
- [ ] The Descent Into Darkness
- [ ] The Sixth Key

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey @GerryLarios 
Great work

It looks awesome, just a small thing instead of character's name, I would appreciate if you add the link to their individual API link 

For e.g. For Gar Goodspeed the link would be https://finalspaceapi.com/api/v0/character/1

Thanks 👍

**Comment by GerryLarios** [comment]
@lelouchB fixed, by the by, I only put the first season, but I will finish all the episodes. 👍

**Review by lelouchB — APPROVED** [review]

**Comment by GerryLarios** [comment]
Sorry to ask, but can you add the label `hacktoberfest-accepted` to my PR?

**Comment by lelouchB** [comment]
I have added Hacktoberfest label to the repo and this PR is merged so it should work for Hacktoberfest. 

But I will also add Hacktoberfest label 🏷 

👍

**Pull request merged**
