### PR TITLE
[ADD] 9 locations

### PR DESCRIPTION
**Pull request by GerryLarios**
#16 
- [x] Earth
- [x] Final Space
- [x] Tera Con Prime
- [x] Inner Space
- [x] Yarno
- [x] Dark Zone
- [x] Deathcropolis
- [x] Lazarus Trap
- [x] The Order of the Twelve

### CODE REVIEW

**Comment by GerryLarios** [comment]
@lelouchB here is the PR. Let me know if we need to change something.

**Review by lelouchB — CHANGES_REQUESTED** [review]
This great 
Obviously the data is less as compared to others.
No worries about that.

Just replace the URL in `img_url` to empty quotes.

I will create a separate issue for images of the locations

Let me know if you would be interested in that?
Thanks 😊

**Review by lelouchB — APPROVED** [review]

**Comment by GerryLarios** [comment]
@lelouchB comments addressed. About the image, let me check how can I work with that 👁️

**Comment by lelouchB** [comment]
@GerryLarios 
I will let you know when this goes live 


Thanks for your amazing work

**Comment by GerryLarios** [comment]
Hello @lelouchB Can you add the label `hacktoberfest-accepted` to my PR?

**Pull request merged**
