### PR TITLE
status icons character

### PR DESCRIPTION
**Pull request by guzbarraf**
Hi @lelouchB, here are the files of the character status icons

### CODE REVIEW

**Review by lelouchB — APPROVED** [review]

**Comment by lelouchB** [comment]
@guzbarraf 
This is great.
Thanks

**Comment by guzbarraf** [comment]
@lelouchB
I liked Final Space and the project is great too.
if there is anything else to do...
with pleasure

**Comment by lelouchB** [comment]
> @lelouchB
> I liked Final Space and the project is great too.
> if there is anything else to do...
> with pleasure

Ofcourse 
Thanks 

I guess REST side of the API is almost complete, will start on GraphQL support soon.

Will keep you posted.  😁

**Comment by guzbarraf** [comment]
> Ofcourse
> Thanks
> 
> I guess REST side of the API is almost complete, will start on GraphQL support soon.
> 
> Will keep you posted. 😁

I'll stay tuned,
cheers!

**Comment by guzbarraf** [comment]
Hi @lelouchB
can you still add hacktoberfest labels to these PRs,
so that they count in the hacktoberfest?

**Pull request merged**
