### PR TITLE
Add SORT param to Character endpoint

### PR DESCRIPTION
**Pull request by Thanarathanam**
Re: #49

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey @Thanarathanam 
This looks good 👍 

I would prefer if you create a file named `options.js` under `backend/helpers`  and export this code as a funtion so that we can resuse it other endpoints too.

Also, there are other parameters like `filter` that need to be added, let me know if you are interested and I will create an issue for you.

Thanks for your contributions

**Review by lelouchB — CHANGES_REQUESTED** [review]
I would prefer if you create a file named options.js under backend/helpers and export this code as a funtion so that we can resuse it other endpoints too.

**Review by lelouchB — APPROVED** [review]

**Review by lelouchB — CHANGES_REQUESTED** [review]
Please make the changes I suggested

**Comment by Thanarathanam** [comment]
@lelouchB It seems the issue already got resolved in #51

**Comment by lelouchB** [comment]
> @lelouchB It seems the issue already got resolved in #51 

Yes, it did
I will go ahead and approve this PR 
You need for Hacktoberfest right?

**Review by lelouchB — APPROVED** [review]

**Comment by Thanarathanam** [comment]
Thanks :)

**Pull request closed without merging**
