### PR TITLE
Added Sort Param to character Endpoint

### LINKED ISSUE #49: Add SORT param to Character endpoint
Add a sort parameter which lets the user sort the response based on `id`.

https://finalspaceapi.com/api/v0/character/?sort=desc
Return the response starting from 40

https://finalspaceapi.com/api/v0/character/?sort=asc
This response will be same as https://finalspaceapi.com/api/v0/character/  i.e. from 1 to 40.

So, https://finalspaceapi.com/api/v0/character/ is the same as https://finalspaceapi.com/api/v0/character/?sort=asc and they both return same response.

Resource: http://expressjs.com/en/api.html#req.query

### PR DESCRIPTION
**Pull request by daretobedifferent18**
#### Related issue
Closes #49 

#### What change is being introduced by this PR?
Created a file options.js inside backend/helpers directory and created sort function and then used that function to sort in characters.api.js file.

### CODE REVIEW

**Review by lelouchB — CHANGES_REQUESTED** [review]
Hey @daretobedifferent18 

I am thinking of exporting a `options` object and then pass that object in`find()` query.

See here 
https://mongoosejs.com/docs/api.html#model_Model.find
I am talking about the optional `options` paramter.

image


You can also add different options in this obejct which are defined here 👍 
https://mongoosejs.com/docs/api.html#query_Query-setOptions


Let me know if you have any questions.

**Comment by daretobedifferent18** [comment]
So I have to define a option object in helpers/options.js file where I should add options of sort and limit?

**Review by lelouchB — COMMENTED** [review]
Nice changes
This was what I was talking about.
Now, we can return other param too from `options.js`

Have you tested this?

Also, I don't quite follow `null,null`

**Comment by daretobedifferent18** [comment]
Yes I have tested this and it is working fine.

#### In find()
#### Parameters
id «Any» value of _id to query by
[projection] «Object|String|Array<String>» optional fields to return, see Query.prototype.select()
[options] «Object» optional see Query.prototype.setOptions()
[callback] «Function»

so I have to put first two arguments as null to pass options object in it.

**Comment by lelouchB** [comment]
Hey @daretobedifferent18 
I guess it will work even if the first two parameters are not present and you just have an empty object `{}` like before..
Can you confirm this?

**Comment by lelouchB** [comment]
About passing `id` and `-id`, 
It makes sense to us but someone may get confused by this.
Whereas on the other hand `asc` and `desc` are self explainatory.

Please change it to `asc` and `desc`

**Comment by daretobedifferent18** [comment]
> About passing `id` and `-id`,
> It makes sense to us but someone may get confused by this.
> Whereas on the other hand `asc` and `desc` are self explainatory.
> 
> Please change it to `asc` and `desc`

done 👍

**Comment by lelouchB** [comment]
Have you tried removing `null,null` ?

**Comment by daretobedifferent18** [comment]
> Have you tried removing `null,null` ?

but that does not work after removing `null, null`

**Comment by lelouchB** [comment]
It should work

Try it like this 

```javascript
await Character.find({ } , options(req.query), (err, characters) => {
//
}
)
```

**Comment by daretobedifferent18** [comment]
> ```js
> await Character.find({ } , options(req.query), (err, characters) => {
> ```

it works only when I have to pass second parameter as `await Character.find({ }, { }, options(req.query), (err, characters)=>{...})`

**Comment by lelouchB** [comment]
Yeah, you are right
So we can pass an empty object in the first param and `null` in second, third is the options.

Can you make these changes.

**Comment by daretobedifferent18** [comment]
> Yeah, you are right
> So we can pass an empty object in the first param and `null` in second, third is the options.
> 
> Can you make these changes.

Done and everything is working fine now.

**Comment by daretobedifferent18** [comment]
I think we the new coming rules on hacktoberfest u have to add hacktoberfest-accepted label as well.
And if everything works fine , pls merge this issue.

**Comment by lelouchB** [comment]
I have added the `hacktoberfest` label on my repo and the issue. So, I guess it should be fine.

Let me know if this PR reflects in your Hacktoberfest dashboard.

I will merge this sometime today or tommorow, after adding the accompanying documentation..

Thanks for your valuable contributions

**Review by lelouchB — APPROVED** [review]

**Comment by daretobedifferent18** [comment]
yeah it is there in my hacktoberfest dashboard showing that the pr is in review process

**Review by lelouchB — APPROVED** [review]

**Pull request merged**
