### PR TITLE
Update character images

### PR DESCRIPTION
**Pull request by SeguinLoic**
It's ok for most of the images ! 
I have never seen this serie before, but it seem to be realy fun ! So .. what is A.V.A ? :') 
Tell me if you want some modifications ;)

- [x]  Gary Goodspeed
- [x]  Mooncake
- [x]  Quinn Ergon
- [x]  Little Cato
- [x]  Avocato
- [x]  KVN
- [x]  Ash Graven
- [x]  Fox
- [x]  H.U.E
- [x]  Clarence
- [x]  Lord Commander
- [x]  Nightfall
- [ ]  A.V.A
- [x]  Tribore
- [x]  John Goodspeed
- [x]  Sheryl Goodspeed
- [x]  Gary Goodspeed (Nightfall's timeline)
- [x]  Bolo
- [x]  Invictus
- [x]  Melanie Dewinter
- [x]  Harp Graven
- [x]  Shannon Thunder
- [x]  Chuck
- [x]  Septim
- [x]  Fraskenhaur

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey @SeguinLoic 
This is awesome.

Actually A.V.A is an AI in the series so there is no actual image of her.

I will go through all the images and let you know if anything needs any modifications. 

Again thanks for this awesome contribution

**Review by lelouchB — COMMENTED** [review]
Hey 
I am going through them and they look quite good 👍 

I would like if you can change the following images 
 - gary_goodspeed : he is the main character and first on in response object. So a good quality image will be really great for him.

- avocato : same, he is also a main character. 
- little_cato
- john_goodspeed 


Other than that just some minor issues with quality in some pics.  If you can please increase these images quality.

- gg_timeline
- sheryl_goodspeed
- tribore 
- shannon_thunder
- quinn_ergon
- nightfall


Thanks you so for your amazing contributions

**Comment by lelouchB** [comment]
Hey @SeguinLoic 
Here is a good resource for images 
https://twitter.com/random_fs_shots

There are many accounts and sub reddit like this 

Hope this helps

**Comment by SeguinLoic** [comment]
Hello @lelouchB 
Thank you for the resources !

I'll check that and do some modifications today ;)

Have a nice day !

**Comment by lelouchB** [comment]
Hey @SeguinLoic 
Maybe after this, you will be interested in #26 ?

Thanks

**Comment by lelouchB** [comment]
Hey @SeguinLoic 
Is there any update on this?
Just checking in 

Thanks

**Comment by SeguinLoic** [comment]
Hey, 

No sorry .. :/ 
Finaly i couldn't work on the project yesterday !

**Comment by lelouchB** [comment]
@SeguinLoic 
No problem

Just keep me updated. Do you think it can be done today? Let me know if you need any help.

I can help with some images.

Thanks

**Comment by SeguinLoic** [comment]
Yeah sure @lelouchB, i can work on the project today ! 
I'll work on  images that you have mentioned in comments. 

But i'm sorry, i won't have time for work on others characters this week.. :/

**Comment by lelouchB** [comment]
No problem
By other characters do you mean the new characters?

They are already done.

**Comment by SeguinLoic** [comment]
Ok, perfect ! 😄

**Review by lelouchB — APPROVED** [review]

**Comment by lelouchB** [comment]
@SeguinLoic 
This looks awesome 
Great additions 

Please  resolve these conflicts.

I plan to merge and ship these images to production sometime tommorow.

Thanks for your work on this .

**Comment by SeguinLoic** [comment]
Thank you @lelouchB ! 

Okay, i have to admite that i'm a totaly beginner with git and github ! I have to understand what is the conflicts 😄

**Comment by lelouchB** [comment]
> Thank you @lelouchB ! 
> 
> Okay, i have to admite that i'm a totaly beginner with git and github ! I have to understand what is the conflicts 😄 

Oh, then it will be a great learning experience.

Resolving conflicts is something that is done quite a lot with PR's.

Let me know if you have any questions or run into an issue.

**Comment by SeguinLoic** [comment]
I'm sorry @lelouchB 
I'm realy lost with that conflicts, i don't know what do that mean .. 😞 

The test says that : "There were conflicts when merging 04fc1f5 into 041cd33 -> [ImgBot] Optimize images (#54)". 
I don't know how can i make my commit good for this ImgBot thing .. 

Do you have an idea ?

**Comment by lelouchB** [comment]
Hey @SeguinLoic  I guess we should take the shortcut on this thing.

- Close this PR
- Copy the images to a secure location on your PC.
-  Delete your fork of this repo.
- Fork this repo again and open it in your PC.
- Copy/Paste the images to the folder
-  Again make a PR

This is not ideal but it should solve this problem.
Thanks

**Pull request closed without merging**
