### PR TITLE
Added Vue Example

### PR DESCRIPTION
**Pull request by Devdre1909**
Added Vue JS example with Fetch API and Axios.
Added Image for the result preview

### CODE REVIEW

**Comment by lelouchB** [comment]
@Devdre1909 
This looks really awesome 👌 
Nice work

I will get to this sometime today and ship it into production as soon  as possible

**Comment by lelouchB** [comment]
Hey @Devdre1909 
Can you make this a column like in React example , this does not look good on Mobile Devices
image

On mobile, this cards become smaller and difficult to read.


There is a small issue of Dark Mode
image


What React example is like
image

Also try to use `Verdana`  font and ` color:"purple",`

Thanks 
Just make these updates and we are good to go

Let me know if you have any questions

**Review by lelouchB — CHANGES_REQUESTED** [review]
Try to use Verdana font and color:"purple",

**Comment by Devdre1909** [comment]
@lelouchB 
Okay. 
I will fix all that, but about the font `Verdana`, it a paid Microsoft font, how do I use it?

**Comment by Devdre1909** [comment]
Hi @lelouchB 

I made the changes as requested. 
I also tried to dynamically change the images using [themeContext](https://v2.docusaurus.io/docs/theme-classic#usethemecontext). I am not really sure if the logic can be used in production. 

Kindly, check it to let me know if It will work, or I should just use one image. 
Thanks.

**Comment by lelouchB** [comment]
@Devdre1909 
Great 
I'll check and let you know 

Thanks

**Comment by lelouchB** [comment]
Hey @Devdre1909 
It's live
https://finalspaceapi.com/docs/vuejs/

I made a few minor changes.

Thanks for this amazing example

**Comment by Devdre1909** [comment]
@lelouchB 
You are welcome.

**Pull request merged**
