### PR TITLE
Refactored frontend/src/pages/index.js 

### PR DESCRIPTION
**Pull request by Pervolarakis**
added _ in front of classes names

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey @Pervolarakis 
Looks Nice 👌 
I hope you have created and served the build folder with these changes.

I'll probably get to this sometime tommorow. Its late night here.

Thanks

**Comment by Pervolarakis** [comment]
Hey,
i didnt push the build folder since it wasnt built already, if you want i can build it and send it over

Thanks

**Comment by lelouchB** [comment]
No need to send the build folder. 

I was just asking.

**Comment by Pervolarakis** [comment]
yep, it works

**Review by lelouchB — CHANGES_REQUESTED** [review]
- Resolve Conflicts
- Create a parent directory.

**Comment by Pervolarakis** [comment]
fixed conflicts,
Do you mind explaining what do you mean by parent directory? you want me to make a new directory for the components inside the page folder?
thanks

**Comment by lelouchB** [comment]
Yes, that's exactly what I meant

Thanks

**Comment by lelouchB** [comment]
Hey
Image formats have bee changed to `.webp`.

Please update
 frontend/src/pages/Components/Body/_Card.js

**Comment by lelouchB** [comment]
Also, what is this submodule `finals-apce-api` ?

**Comment by Pervolarakis** [comment]
oops, you mean the folder inside the frontend folder right? i pull the whole rep inside there by mistake. you can ignore that

**Comment by lelouchB** [comment]
Ok, 👍 
I will proceed to merger this then.

Thanks for your contribution.

Feel free to look at other issues or create your own.

**Comment by Pervolarakis** [comment]
you need to delete the folder dont leave it in there. its just an old pull

**Comment by lelouchB** [comment]
I have deleted it.
Thanks

**Pull request merged**
