### PR TITLE
add Vanilla js and Vanilla js + axios static examples

### PR DESCRIPTION
**Pull request by PSmigielski**
I added vanilla js and vanilla js + axios static examples, beacuse docusaurus live code editor didn't work very well with js code.

### CODE REVIEW

**Comment by lelouchB** [comment]
Hey @PSmigielski 
Docusarus uses React Live for the interactive coder so it will only support React.

Also, I was not able to figure out how to import axios in that love coder so static examples are good too 


Thanks

**Comment by lelouchB** [comment]
@PSmigielski 
Can you make the suggested changes?

**Comment by lelouchB** [comment]
@PSmigielski 

Any update on this?

**Comment by PSmigielski** [comment]
No it works very well

**Comment by PSmigielski** [comment]
No it works very well

**Comment by lelouchB** [comment]
@PSmigielski 
Have you made the requested changes?

**Comment by PSmigielski** [comment]
yep

**Review by lelouchB — CHANGES_REQUESTED** [review]
> 
> 
> yep

I am not seeing any changes

**Comment by PSmigielski** [comment]
also i added more data about characters to examples

**Comment by lelouchB** [comment]
Great 👍 
Can you also add a screenshot of the complete output of the code
So that readers know exactly what this code render

**Comment by PSmigielski** [comment]
Something more?

**Comment by PSmigielski** [comment]
?

**Review by lelouchB — COMMENTED** [review]
> ?

Oh Sorry
Kind of missed this PR
Nothing more 
Just make the requested changes and we are good to go for next production build.

Thanks

**Comment by PSmigielski** [comment]
ok so i added javascript media queries to make card style mobile friendly, colors to labels and blank lines in code between elements

**Comment by lelouchB** [comment]
> ok so i added javascript media queries to make card style mobile friendly, colors to labels and blank lines in code between elements

Nice just update the image, preferably in webp format and we are good to go 
Thanks 
Nice Work 👌

**Review by lelouchB — APPROVED** [review]

**Comment by lelouchB** [comment]
Great
I wi ship it to production build tommorow.

**Pull request merged**
