### PR TITLE
 new logo added

### PR DESCRIPTION
**Pull request by deepharshsri**

### CODE REVIEW

**Comment by lelouchB** [comment]
@deepharshsri 
I am not seeing any logo.

**Comment by deepharshsri** [comment]
Hey, I have updated the logo in frontend -> static ->img ->logo.png.
I have deleted the previous logo.png and replace it with mine new one.

**Comment by deepharshsri** [comment]
Should I have to add it with another name?

**Comment by lelouchB** [comment]
@deepharshsri  I am not seeing any image in Files Chnaged.

**Comment by deepharshsri** [comment]
Ok let me check.

**Comment by deepharshsri** [comment]
Can I  delete the old logo?

**Comment by lelouchB** [comment]
@deepharshsri 
Awesome 👌 
Nice logo.

I would like to wait for other contributors to finish too.


I plan to merge all of the PR  and revert all but one.

Thanks a lot for your contributions to this project.

**Review by lelouchB — APPROVED** [review]

**Comment by deepharshsri** [comment]
Thank you very much 😊

**Comment by lelouchB** [comment]
Hey @deepharshsri 
I have another designing issue if you would like to work on it. ?

**Comment by deepharshsri** [comment]
Yes, I will love too

**Comment by lelouchB** [comment]
> Yes, I will love too
> 

Cool 
I will mention you in that issue.
I will get to it sometime tommorow. 

Thanks

**Review by lelouchB — CHANGES_REQUESTED** [review]
Logo is missing

**Comment by deepharshsri** [comment]
Hello, I think it's happening because I have sent a pull request to
the main it's my fault.
Can you reassign me again so that I make PR to the endpoint branch?

**Comment by deepharshsri** [comment]
I am still assigned to issue or not?
I have sent this time to the endpoint with updated one.

**Comment by lelouchB** [comment]
https://github.com/lelouchB/final-space-api/pull/82#issuecomment-705585306

**Comment by deepharshsri** [comment]
Ok, so I think all my previous PR gets closed now.
So can I make a new fresh PR now?

**Comment by lelouchB** [comment]
yes, that is what I was saying

Please make a new PR 

Thanks

**Comment by deepharshsri** [comment]
OK I have sent the PR please check.

**Pull request closed without merging**
