### PR TITLE
New charecters

### PR DESCRIPTION
**Pull request by stevenjburrows**
new pull request from #23  to change the destination branch for issue #18

### CODE REVIEW

**Comment by stevenjburrows** [comment]
I can work on the images tomorrow if you want

**Comment by lelouchB** [comment]
@stevenjburrows 
As I said, will add these characters to the API response once images for these characters are ready. I will notify you once I do that.
Thanks for this amazing contribution

**Comment by lelouchB** [comment]
@stevenjburrows 
The new characters are live
Here is the blog for this https://finalspaceapi.com/blog/15characters

Try them here https://finalspaceapi.com/api/v0/character

Thanks for your contributions

**Comment by stevenjburrows** [comment]
@lelouchB it looks good, glad I could help out

**Pull request merged**
